<?php

use Illuminate\Database\Seeder;

class pro_zonesSeeder extends Seeder
{
    /**
     * Run the database seeds.
     *
     * @return void
     */
    public function run()
    {
        /*DB::table('pro_zones')->insert([
            'slug'=>'मेची',
            'name'=>'मेची',
            'name_eng'=>'Mechi',
            'description'=>'',
            'description_eng'=>'',
            'image'=>'',
            'coordinates'=>'',
            'region_id'=>1,
            'status'=>1,
        ]);*/
        DB::table('pro_zones')->insert([
            'slug'=>'कोशी',
            'name'=>'कोशी',
            'name_eng'=>'Koshi',
            'description'=>'',
            'description_eng'=>'',
            'image'=>'',
            'coordinates'=>'',
            'region_id'=>1,
            'status'=>1,
        ]);
        DB::table('pro_zones')->insert([
            'slug'=>'सगरमाथा',
            'name'=>'सगरमाथा',
            'name_eng'=>'Sagarmatha',
            'description'=>'',
            'description_eng'=>'',
            'image'=>'',
            'coordinates'=>'',
            'region_id'=>1,
            'status'=>1,
        ]);
        DB::table('pro_zones')->insert([
            'slug'=>'जनकपुर',
            'name'=>'जनकपुर',
            'name_eng'=>'Janakpur',
            'description'=>'',
            'description_eng'=>'',
            'image'=>'',
            'coordinates'=>'',
            'region_id'=>2,
            'status'=>1,
        ]);
        DB::table('pro_zones')->insert([
            'slug'=>'बागमति',
            'name'=>'बागमति',
            'name_eng'=>'Bagmati',
            'description'=>'',
            'description_eng'=>'',
            'image'=>'',
            'coordinates'=>'',
            'region_id'=>2,
            'status'=>1,
        ]);
        DB::table('pro_zones')->insert([
            'slug'=>'नारायणी',
            'name'=>'नारायणी',
            'name_eng'=>'Narayani',
            'description'=>'',
            'description_eng'=>'',
            'image'=>'',
            'coordinates'=>'',
            'region_id'=>2,
            'status'=>1,
        ]);
        DB::table('pro_zones')->insert([
            'slug'=>'गण्डकी',
            'name'=>'गण्डकी',
            'name_eng'=>'Gandaki',
            'description'=>'',
            'description_eng'=>'',
            'image'=>'',
            'coordinates'=>'',
            'region_id'=>3,
            'status'=>1,
        ]);
        DB::table('pro_zones')->insert([
            'slug'=>'धवलागिरी',
            'name'=>'धवलागिरी',
            'name_eng'=>'Dhawalagiri',
            'description'=>'',
            'description_eng'=>'',
            'image'=>'',
            'coordinates'=>'',
            'region_id'=>3,
            'status'=>1,
        ]);
        DB::table('pro_zones')->insert([
            'slug'=>'लुम्विनी',
            'name'=>'लुम्विनी',
            'name_eng'=>'Lumbini',
            'description'=>'',
            'description_eng'=>'',
            'image'=>'',
            'coordinates'=>'',
            'region_id'=>3,
            'status'=>1,
        ]);
        DB::table('pro_zones')->insert([
            'slug'=>'राप्ती',
            'name'=>'राप्ती',
            'name_eng'=>'Rapti',
            'description'=>'',
            'description_eng'=>'',
            'image'=>'',
            'coordinates'=>'',
            'region_id'=>4,
            'status'=>1,
        ]);
        DB::table('pro_zones')->insert([
            'slug'=>'भेरी',
            'name'=>'भेरी',
            'name_eng'=>'Bheri',
            'description'=>'',
            'description_eng'=>'',
            'image'=>'',
            'coordinates'=>'',
            'region_id'=>4,
            'status'=>1,
        ]);
        DB::table('pro_zones')->insert([
            'slug'=>'कर्णाली',
            'name'=>'कर्णाली',
            'name_eng'=>'Karnali',
            'description'=>'',
            'description_eng'=>'',
            'image'=>'',
            'coordinates'=>'',
            'region_id'=>4,
            'status'=>1,
        ]);
        DB::table('pro_zones')->insert([
            'slug'=>'सेती',
            'name'=>'सेती',
            'name_eng'=>'Seti',
            'description'=>'',
            'description_eng'=>'',
            'image'=>'',
            'coordinates'=>'',
            'region_id'=>5,
            'status'=>1,
        ]);
        DB::table('pro_zones')->insert([
            'slug'=>'महाकाली',
            'name'=>'महाकाली',
            'name_eng'=>'Mahakali',
            'description'=>'',
            'description_eng'=>'',
            'image'=>'',
            'coordinates'=>'',
            'region_id'=>5,
            'status'=>1,
        ]);
    }
}
